included:
  - Apps
  - Modules
  - Tests

excluded:
  - .build
  - .xcodebuild
  - .tuist
  - dist

disabled_rules:
  - trailing_comma

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports

line_length:
  warning: 140
  error: 180
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 350
  error: 500

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length:
    warning: 2

reporter: xcode
